//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.TL.CoreSite.EnterpriseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://TlSamples", ConfigurationName="EnterpriseService.IDataService", CallbackContract=typeof(HomeWork.TL.CoreSite.EnterpriseService.IDataServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://TlSamples/IDataService/GetOrderById", ReplyAction="https://TlSamples/IDataService/GetOrderByIdResponse")]
        Enterprise.Service.Shared.Contracts.DataContracts.OrderDto GetOrderById(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://TlSamples/IDataService/GetOrderById", ReplyAction="https://TlSamples/IDataService/GetOrderByIdResponse")]
        System.Threading.Tasks.Task<Enterprise.Service.Shared.Contracts.DataContracts.OrderDto> GetOrderByIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://TlSamples/IDataService/GetOrderByIdDuplex")]
        void GetOrderByIdDuplex(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://TlSamples/IDataService/GetOrderByIdDuplex")]
        System.Threading.Tasks.Task GetOrderByIdDuplexAsync(int orderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://TlSamples/IDataService/OrderResult")]
        void OrderResult(Enterprise.Service.Shared.Contracts.DataContracts.OrderDto order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : HomeWork.TL.CoreSite.EnterpriseService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.DuplexClientBase<HomeWork.TL.CoreSite.EnterpriseService.IDataService>, HomeWork.TL.CoreSite.EnterpriseService.IDataService {
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Enterprise.Service.Shared.Contracts.DataContracts.OrderDto GetOrderById(int orderId) {
            return base.Channel.GetOrderById(orderId);
        }
        
        public System.Threading.Tasks.Task<Enterprise.Service.Shared.Contracts.DataContracts.OrderDto> GetOrderByIdAsync(int orderId) {
            return base.Channel.GetOrderByIdAsync(orderId);
        }
        
        public void GetOrderByIdDuplex(int orderId) {
            base.Channel.GetOrderByIdDuplex(orderId);
        }
        
        public System.Threading.Tasks.Task GetOrderByIdDuplexAsync(int orderId) {
            return base.Channel.GetOrderByIdDuplexAsync(orderId);
        }
    }
}
